<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>0d73987f-440c-4e9e-80d0-f1ff4a776bef</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_beige_creme_45</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[2]/div[1]/div[3]/div[1]/div[1]/div[3]/div[1]/div[2]/div[1]/div[2]/div[9]/ul[1]/li[3]/a[1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@title,'Beige / Creme (45)')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry></entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>title</name>
        <type>Main</type>
        <value>Beige / Creme (45)</value>
        <webElementGuid>a8ef4ba1-3984-4cd3-bad9-6608551f2745</webElementGuid>
    </webElementProperties>
</WebElementEntity>