<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>906fa76e-e8a4-4641-a05a-79217c825a30</elementGuidId>
    <imagePath></imagePath>
    <name>li_date_items</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[2]/div[3]/ul[1]/li[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[role][tabindex='\30 ']</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@class,'MuiButtonBase-root MuiMenuItem-root MuiMenuItem-gutters MuiMenuItem-root MuiMenuItem-gutters css-buwmil')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>MuiButtonBase-root MuiMenuItem-root MuiMenuItem-gutters MuiMenuItem-root MuiMenuItem-gutters css-buwmil</value>
        <webElementGuid>6f98b3cb-85ee-4b5d-8e82-f2ce03d61414</webElementGuid>
    </webElementProperties>
</WebElementEntity>