<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>af71027e-6370-471c-92b4-59ceb95a7414</elementGuidId>
    <imagePath></imagePath>
    <name>p_object</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[2]/div[1]/span[1]/div[1]/p[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[aria-label='Cao\ Hoang\ Dung']</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@class,'MuiTypography-root MuiTypography-body1 MuiTypography-noWrap css-1fmtder')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>MuiTypography-root MuiTypography-body1 MuiTypography-noWrap css-1fmtder</value>
        <webElementGuid>035fcc24-8778-4d9d-9032-dbaa68cc5065</webElementGuid>
    </webElementProperties>
</WebElementEntity>